#Put the name of the repo as it is on github. Comment this variable when you are testing locally. Uncomment before pushing to github.
baseurl: /club-website-template

#The title appears on the first page
title: The Club

#The logo appears as a small circular image above the title
logo: /assets/img/logo.png 

#The font for everything in the header
headerFont:

#The fontcolor of everything in the header
headerFontColor:

#The background of the header. If you want image, leave the headerBackgroundColor empty and vice-versa
headerBackgroundImage:
headerBackgroundImageOpacity:
headerActivePageButtonBackground:
headerBackgroundColor: rgba(255,0,0,0.5)

#The font for everything in the footer
footerFont: Arial, Helvetica, sans-serif

#The fontcolor of everything in the footer
footerFontColor: white

#The background color of the footer
footerBackgroundColor: black
footerBackgroundImage: /assets/img/bg/background.jpg

#The background for each event page
eventPageBackgroundImage: 
eventPageBackgroundColor:

#The font for each event page
eventPageHeadingFont:
eventPageHeadingFontColor:
eventPageOtherFont:
eventPageOtherFontColor:

#The list of pages on your website
pageList:
  - name: Home
    url: /home.html
  - name: Past Events
    url: /pastEvents.html
  - name: People
    url: /people.html

#This appears on the footer
maintainedBy: club

#This appears on the footer. Put the name of the website builder here.
builtBy: me
builtByURL: https://github.io/hopefullyDoesntExist

collections:
  events:
    output: true
  